/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIImageGenerator: typeof import('./src/components/AIImageGenerator.vue')['default']
    ApiErrorBanner: typeof import('./src/components/common/ApiErrorBanner.vue')['default']
    AuroraBackground: typeof import('./src/components/ui/AuroraBackground.vue')['default']
    CapabilitiesMatrix: typeof import('./src/components/home/CapabilitiesMatrix.vue')['default']
    ChatPanel: typeof import('./src/components/deepseek/ChatPanel.vue')['default']
    CodeShowcase: typeof import('./src/components/home/CodeShowcase.vue')['default']
    ConfigPanel: typeof import('./src/components/deepseek/ConfigPanel.vue')['default']
    CoreArchitecture: typeof import('./src/components/home/CoreArchitecture.vue')['default']
    CustomCursor: typeof import('./src/components/ui/CustomCursor.vue')['default']
    DeepseekDemo: typeof import('./src/components/DeepseekDemo.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    EmptyState: typeof import('./src/components/deepseek/chat/EmptyState.vue')['default']
    FollowUpSuggestions: typeof import('./src/components/deepseek/chat/FollowUpSuggestions.vue')['default']
    GameGuide: typeof import('./src/components/game/GameGuide.vue')['default']
    GameIntro: typeof import('./src/components/game/GameIntro.vue')['default']
    GameOptions: typeof import('./src/components/game/GameOptions.vue')['default']
    GameOverModal: typeof import('./src/components/game/GameOverModal.vue')['default']
    GameProgress: typeof import('./src/components/game/GameProgress.vue')['default']
    GameScene: typeof import('./src/components/game/GameScene.vue')['default']
    GameStatusBar: typeof import('./src/components/game/GameStatusBar.vue')['default']
    GiaoGame: typeof import('./src/components/GiaoGame.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    ImageGeneratorForm: typeof import('./src/components/image-generator/ImageGeneratorForm.vue')['default']
    ImageGeneratorResults: typeof import('./src/components/image-generator/ImageGeneratorResults.vue')['default']
    MainFooter: typeof import('./src/components/home/MainFooter.vue')['default']
    MessageItem: typeof import('./src/components/deepseek/chat/MessageItem.vue')['default']
    ModelSelector: typeof import('./src/components/deepseek/ModelSelector.vue')['default']
    PromptExampleModal: typeof import('./src/components/PromptExampleModal.vue')['default']
    PromptLibrary: typeof import('./src/components/PromptLibrary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioBackgroundCG: typeof import('./src/components/game/ScenarioBackgroundCG.vue')['default']
    SessionSidebar: typeof import('./src/components/deepseek/SessionSidebar.vue')['default']
    ThinkingProcess: typeof import('./src/components/deepseek/chat/ThinkingProcess.vue')['default']
    TransformModal: typeof import('./src/components/deepseek/modals/TransformModal.vue')['default']
    ValueShowcase: typeof import('./src/components/home/ValueShowcase.vue')['default']
  }
}
