/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIImageGenerator: typeof import('./src/components/AIImageGenerator.vue')['default']
    ApiUrlInput: typeof import('./src/components/ApiUrlInput.vue')['default']
    DeepseekDemo: typeof import('./src/components/DeepseekDemo.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GameGuide: typeof import('./src/components/game/GameGuide.vue')['default']
    GameIntro: typeof import('./src/components/game/GameIntro.vue')['default']
    GameOptions: typeof import('./src/components/game/GameOptions.vue')['default']
    GameOverModal: typeof import('./src/components/game/GameOverModal.vue')['default']
    GameProgress: typeof import('./src/components/game/GameProgress.vue')['default']
    GameScene: typeof import('./src/components/game/GameScene.vue')['default']
    GameStatusBar: typeof import('./src/components/game/GameStatusBar.vue')['default']
    GiaoGame: typeof import('./src/components/GiaoGame.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MessageNotification: typeof import('./src/components/MessageNotification.vue')['default']
    ModalDialog: typeof import('./src/components/ModalDialog.vue')['default']
    ProgressPanel: typeof import('./src/components/ProgressPanel.vue')['default']
    PromptExampleModal: typeof import('./src/components/PromptExampleModal.vue')['default']
    PromptLibrary: typeof import('./src/components/PromptLibrary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
